#!/usr/bin/env python3
"""
SIH26153 -- JSONL-to-firewall Rule Generator

Reads detected anomalies from JSONL files and generates ready-to-use
firewall rules for multiple backends:
  - Linux: iptables, nftables, ufw
  - macOS: pf
  - Windows: netsh advfirewall

Usage:
    python jsonl_to_iptables.py                           # Read default anomalies file
    python jsonl_to_iptables.py --input data/anomalies.jsonl  # Custom input
    python jsonl_to_iptables.py --output rules.sh         # Save to file
    python jsonl_to_iptables.py --format iptables          # iptables only
    python jsonl_to_iptables.py --format nftables          # nftables only
    python jsonl_to_iptables.py --format all               # All formats (platform-aware)
    python jsonl_to_iptables.py --apply                    # Apply rules (needs admin on Windows, root on Linux)
    python jsonl_to_iptables.py --severity CRITICAL        # Only block critical IPs

Note: On Windows, install Npcap first: https://npcap.com/#download
"""

import argparse
import json
import platform
import sys
from datetime import datetime, timezone

UTC = timezone.utc
from pathlib import Path
from typing import Dict, List

PROJECT_ROOT = Path(__file__).parent
DEFAULT_ANOMALIES = PROJECT_ROOT / "data" / "anomalies.jsonl"
DEFAULT_OUTPUT = PROJECT_ROOT / "data" / "firewall_rules.sh"

# Ports to protect
HIGH_RISK_PORTS = {22, 23, 3389, 5900, 3306, 5432, 6379, 27017, 1433, 445}


def load_anomalies(path: Path, severity_filter: str = None) -> List[Dict]:
    """Load anomalies from a JSONL file."""
    anomalies = []
    if not path.exists():
        return anomalies

    with open(path, encoding="utf-8") as f:
        content = f.read().strip()
    if not content:
        return anomalies

    # Try JSON array first
    try:
        parsed = json.loads(content)
        if isinstance(parsed, list):
            anomalies = parsed
        elif isinstance(parsed, dict):
            anomalies = [parsed]
    except json.JSONDecodeError:
        # Fall back to JSONL
        for line in content.splitlines():
            line = line.strip()
            if line:
                try:
                    anomalies.append(json.loads(line))
                except json.JSONDecodeError:
                    continue

    if severity_filter:
        anomalies = [a for a in anomalies if a.get("severity") == severity_filter.upper()]

    return anomalies


def extract_blocked_ips(anomalies: List[Dict]) -> Dict[str, Dict]:
    """Extract unique attacker IPs with their worst severity and attack type."""
    ip_data = {}
    severity_rank = {"CRITICAL": 4, "HIGH": 3, "MEDIUM": 2, "LOW": 1}

    for a in anomalies:
        src_ip = a.get("src_ip", "")
        if not src_ip or src_ip in ("", "\u2014"):
            continue

        # Handle comma-separated IPs (distributed attacks)
        ips = [ip.strip() for ip in src_ip.split(",") if ip.strip()]
        severity = a.get("severity", "MEDIUM")
        sev_rank = severity_rank.get(severity, 0)

        for ip in ips:
            if ip not in ip_data or sev_rank > severity_rank.get(ip_data[ip]["severity"], 0):
                ip_data[ip] = {
                    "severity": severity,
                    "anomaly_type": a.get("anomaly_type", "Unknown"),
                    "dst_port": a.get("dst_port", 0),
                    "confidence": a.get("confidence", 0),
                    "mitre": a.get("mitre", {}),
                    "timestamp": a.get("timestamp", ""),
                }

    return ip_data


# -- Rule Generators ---------------------------------------------------------


def generate_iptables_rules(ip_data: Dict[str, Dict]) -> List[str]:
    """Generate iptables rules for blocking attacker IPs."""
    rules = []
    rules.append("# -- iptables rules generated by SIH26153 NetWatch --")
    rules.append(f"# Generated: {datetime.now(UTC).isoformat()}")
    rules.append(f"# IPs to block: {len(ip_data)}")
    rules.append("")

    # Create custom chain for easy management
    rules.append("# Create/flush NETWATCH chain")
    rules.append("iptables -N NETWATCH 2>/dev/null || iptables -F NETWATCH")
    rules.append("")

    for ip, data in sorted(ip_data.items(), key=lambda x: (
        {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}.get(x[1]["severity"], 4)
    )):
        sev = data["severity"]
        atype = data["anomaly_type"]
        port = data["dst_port"]
        conf = data["confidence"]

        rules.append(f"# [{sev}] {atype} from {ip} (confidence: {conf:.0%})")

        if port and port in HIGH_RISK_PORTS:
            # Block specific port for high-risk services
            rules.append(f"iptables -A NETWATCH -s {ip} -p tcp --dport {port} -j DROP")
            rules.append(f"iptables -A NETWATCH -s {ip} -p udp --dport {port} -j DROP")
        else:
            # Block all traffic from the IP
            rules.append(f"iptables -A NETWATCH -s {ip} -j DROP")

        # Log before drop for forensics
        rules.append(f'iptables -A NETWATCH -s {ip} -j LOG --log-prefix "NETWATCH-{sev}: "')
        rules.append("")

    # Insert the chain into INPUT
    rules.append("# Activate the NETWATCH chain")
    rules.append("iptables -I INPUT 1 -j NETWATCH")
    rules.append("")

    return rules


def generate_nftables_rules(ip_data: Dict[str, Dict]) -> List[str]:
    """Generate nftables rules for blocking attacker IPs."""
    rules = []
    rules.append("# -- nftables rules generated by SIH26153 NetWatch --")
    rules.append(f"# Generated: {datetime.now(UTC).isoformat()}")
    rules.append("")

    rules.append("# Create table and set")
    rules.append("add table inet netwatch")
    rules.append("add set inet netwatch blocked_ips { type ipv4_addr\\; }")
    rules.append("")

    # Add IPs to the set
    for ip, data in ip_data.items():
        sev = data["severity"]
        atype = data["anomaly_type"]
        rules.append(f"# [{sev}] {atype}")
        rules.append(f"add element inet netwatch blocked_ips {{ {ip} }}")

    rules.append("")
    rules.append("# Drop rule using the set")
    rules.append("add rule inet netwatch input ip saddr @blocked_ips drop")
    rules.append("")

    return rules


def generate_ufw_commands(ip_data: Dict[str, Dict]) -> List[str]:
    """Generate ufw commands for blocking attacker IPs."""
    commands = []
    commands.append("# -- ufw commands generated by SIH26153 NetWatch --")
    commands.append(f"# Generated: {datetime.now(UTC).isoformat()}")
    commands.append("")

    for ip, data in ip_data.items():
        sev = data["severity"]
        atype = data["anomaly_type"]
        commands.append(f"# [{sev}] {atype}")
        commands.append(f"ufw deny from {ip} to any")
        commands.append("")

    return commands


def generate_netsh_commands(ip_data: Dict[str, Dict]) -> List[str]:
    """Generate Windows netsh advfirewall commands for blocking attacker IPs."""
    commands = []
    commands.append("# -- Windows netsh commands generated by SIH26153 NetWatch --")
    commands.append(f"# Generated: {datetime.now(UTC).isoformat()}")
    commands.append("")
    commands.append("REM Run these commands in an elevated (Administrator) Command Prompt.")
    commands.append("")

    for ip, data in ip_data.items():
        sev = data["severity"]
        atype = data["anomaly_type"]
        port = data.get("dst_port", 0)
        rule_name = f"NetWatch-{sev}-{ip.replace('.', '-')}"

        commands.append(f"REM [{sev}] {atype} from {ip}")
        if port and port in HIGH_RISK_PORTS:
            # Block specific port for high-risk services
            commands.append(
                f'netsh advfirewall firewall add rule name="{rule_name}-TCP" '
                f'dir=in action=block protocol=tcp remoteip={ip} localport={port}'
            )
            commands.append(
                f'netsh advfirewall firewall add rule name="{rule_name}-UDP" '
                f'dir=in action=block protocol=udp remoteip={ip} localport={port}'
            )
        else:
            # Block all traffic from the IP
            commands.append(
                f'netsh advfirewall firewall add rule name="{rule_name}" '
                f'dir=in action=block remoteip={ip}'
            )
        commands.append("")

    return commands


def generate_sudoers_dropin(ip_data: Dict[str, Dict]) -> str:
    """Generate a sudoers drop-in file for non-interactive rule application (Linux only)."""
    lines = []
    lines.append("# /etc/sudoers.d/netwatch-auto-block")
    lines.append(f"# Generated by SIH26153 NetWatch on {datetime.now(UTC).isoformat()}")
    lines.append("# Allows the netwatch user to apply firewall rules without password")
    lines.append("")

    # Allow running the iptables script
    script_path = DEFAULT_OUTPUT
    lines.append("# Allow applying generated rules")
    lines.append(f"root ALL=(root) NOPASSWD: {script_path}")
    lines.append("")

    # Allow specific iptables commands for the netwatch user
    lines.append("# Allow iptables management for NETWATCH chain")
    for ip in ip_data:
        lines.append(f"root ALL=(root) NOPASSWD: /sbin/iptables -A NETWATCH -s {ip} *")
        lines.append(f"root ALL=(root) NOPASSWD: /sbin/iptables -D NETWATCH -s {ip} *")

    lines.append("")
    return "\n".join(lines)


def apply_rules(rules: List[str], dry_run: bool = False) -> bool:
    """Apply firewall rules. Requires root on Linux/macOS, admin on Windows."""
    import subprocess

    is_windows = platform.system() == "Windows"

    for rule in rules:
        rule = rule.strip()
        if not rule or rule.startswith("#"):
            continue

        if dry_run:
            print(f"  [DRY RUN] {rule}")
            continue

        try:
            # On Windows, netsh commands need shell=True to parse correctly
            # On Linux, iptables/nft commands can be split directly
            if is_windows:
                result = subprocess.run(
                    rule, shell=True, capture_output=True, text=True, timeout=10
                )
            else:
                result = subprocess.run(
                    rule.split(), capture_output=True, text=True, timeout=10
                )
            if result.returncode != 0:
                print(f"  [ERROR] {rule}: {result.stderr.strip()}")
                return False
            else:
                print(f"  [OK] {rule}")
        except Exception as e:
            print(f"  [ERROR] {rule}: {e}")
            return False

    return True


# -- Main --------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="SIH26153 -- JSONL-to-firewall Rule Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate rules from default anomalies file
  python jsonl_to_iptables.py

  # Only block CRITICAL severity IPs
  python jsonl_to_iptables.py --severity CRITICAL

  # Generate all formats and save
  python jsonl_to_iptables.py --format all --output rules.sh

  # Generate Windows netsh commands only
  python jsonl_to_iptables.py --format netsh --output data/rules.bat

  # Dry-run apply
  python jsonl_to_iptables.py --apply --dry-run
        """,
    )
    parser.add_argument("--input", "-i", type=Path, default=DEFAULT_ANOMALIES,
                        help="Input JSONL anomalies file")
    parser.add_argument("--output", "-o", type=Path, default=DEFAULT_OUTPUT,
                        help="Output rules file")
    parser.add_argument("--format", "-f", choices=["iptables", "nftables", "ufw", "netsh", "all"],
                        default="all", help="Output format")
    parser.add_argument("--severity", "-s", default=None,
                        help="Only block IPs with this severity or higher")
    parser.add_argument("--apply", action="store_true",
                        help="Apply rules immediately (requires root/admin)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be applied without applying")
    parser.add_argument("--sudoers", action="store_true",
                        help="Generate sudoers drop-in file (Linux only)")
    parser.add_argument("--json", action="store_true",
                        help="Output as JSON instead of shell script")
    args = parser.parse_args()

    # Load anomalies
    anomalies = load_anomalies(args.input, severity_filter=args.severity)
    if not anomalies:
        print(f"No anomalies found in {args.input}")
        sys.exit(0)

    print(f"Loaded {len(anomalies)} anomalies from {args.input}")

    # Extract IPs to block
    ip_data = extract_blocked_ips(anomalies)
    print(f"Found {len(ip_data)} unique attacker IPs to block")

    if not ip_data:
        print("No IPs to block.")
        sys.exit(0)

    # Generate rules
    all_output = []

    if args.json:
        output = json.dumps({
            "generated_at": datetime.now(UTC).isoformat(),
            "anomalies_count": len(anomalies),
            "blocked_ips": len(ip_data),
            "ips": {ip: {
                "severity": d["severity"],
                "anomaly_type": d["anomaly_type"],
            } for ip, d in ip_data.items()},
            "iptables": generate_iptables_rules(ip_data),
            "nftables": generate_nftables_rules(ip_data),
            "ufw": generate_ufw_commands(ip_data),
            "netsh": generate_netsh_commands(ip_data),
        }, indent=2)
        all_output.append(output)
    else:
        all_output.append("#!/bin/bash")
        all_output.append("# SIH26153 NetWatch -- Firewall Rules")
        all_output.append(f"# Generated: {datetime.now(UTC).isoformat()}")
        all_output.append(f"# Source: {args.input}")
        all_output.append("")

        if args.format in ("iptables", "all"):
            all_output.extend(generate_iptables_rules(ip_data))

        if args.format in ("nftables", "all"):
            all_output.extend(generate_nftables_rules(ip_data))

        if args.format in ("ufw", "all"):
            all_output.extend(generate_ufw_commands(ip_data))

        if args.format in ("netsh", "all"):
            all_output.extend(generate_netsh_commands(ip_data))

    # Sudoers (Linux only)
    if args.sudoers:
        if platform.system() == "Windows":
            print("Warning: --sudoers is Linux only. Use --format netsh for Windows.")
        else:
            sudoers_path = PROJECT_ROOT / "data" / "netwatch-auto-block.sudoers"
            sudoers_content = generate_sudoers_dropin(ip_data)
            sudoers_path.write_text(sudoers_content)
            print(f"Sudoers drop-in saved to {sudoers_path}")

    # Write output
    content = "\n".join(all_output)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content)
    print(f"Rules saved to {args.output}")

    # Apply if requested
    if args.apply:
        print("\nApplying rules...")
        success = apply_rules(
            generate_iptables_rules(ip_data),
            dry_run=args.dry_run
        )
        if success:
            print("Rules applied successfully!")
        else:
            print("Some rules failed to apply.")
            sys.exit(1)

    # Summary
    print(f"\n{'='*50}")
    print("  Summary")
    print(f"{'='*50}")
    print(f"  Anomalies processed: {len(anomalies)}")
    print(f"  IPs to block:        {len(ip_data)}")
    critical = sum(1 for d in ip_data.values() if d["severity"] == "CRITICAL")
    high = sum(1 for d in ip_data.values() if d["severity"] == "HIGH")
    print(f"  CRITICAL:            {critical}")
    print(f"  HIGH:                {high}")
    print(f"  Output format:       {args.format}")
    print(f"  Platform:            {platform.system()}")
    print(f"{'='*50}")


if __name__ == "__main__":
    main()
